In [ ]:
### Test Wasse

In [133]:
import numpy as np
import kcluster
import importlib
importlib.reload(kcluster)

<module 'kcluster' from 'D:\\Desktop\\CoursMVA\\ComputationalOptTransport\\Project\\HOTT\\kcluster.py'>

In [134]:
Data = np.array([[0.2,0.8],[0.3,0.7], [0.7,0.3],[0.25,0.85], [0.65,0.35], [0.45,0.55]])

In [137]:
C = np.array([[0,1],[1,0]])
y = np.array([0,0,0,1,1])

In [138]:
dataDist, datalabels, barycenters, dataHist, listPvalue, listInfoDist = kcluster.kclustering(2, Data, C, y, max_iter = 15, reg = 0.01, pVal = False, verbose = False)

Loop n° : 0
Distance Between
[0.2 0.8]
[0.7 0.3]
is
0.49999999999999994
Distance Between
[0.2 0.8]
[0.2 0.8]
is
0.0
Distance Between
[0.3 0.7]
[0.7 0.3]
is
0.39999999999999997
Distance Between
[0.3 0.7]
[0.2 0.8]
is
0.09999999999999998
Distance Between
[0.7 0.3]
[0.7 0.3]
is
0.0
Distance Between
[0.7 0.3]
[0.2 0.8]
is
0.49999999999999994
Distance Between
[0.25 0.85]
[0.7 0.3]
is
0.0
Distance Between
[0.25 0.85]
[0.2 0.8]
is
0.0
Distance Between
[0.65 0.35]
[0.7 0.3]
is
0.04999999999999993
Distance Between
[0.65 0.35]
[0.2 0.8]
is
0.45
Distance Between
[0.45 0.55]
[0.7 0.3]
is
0.24999999999999994
Distance Between
[0.45 0.55]
[0.2 0.8]
is
0.25
Barycenters [[0.7 0.3]
 [0.2 0.8]]
distances [[0.5  0.  ]
 [0.4  0.1 ]
 [0.   0.5 ]
 [0.   0.  ]
 [0.05 0.45]
 [0.25 0.25]]
DataLabels [1. 1. 0. 0. 0. 0.]
Loop n° : 1
DataLabel_k [[0.7  0.3 ]
 [0.25 0.85]
 [0.65 0.35]
 [0.45 0.55]]
Barycenters
[0.53182156 0.49229213]
DataLabel_k [[0.2 0.8]
 [0.3 0.7]]
Barycenters
[0.27271478 0.72728522]
Distance to

(array([0.00000000e+00, 0.00000000e+00, 3.49944983e-01, 0.00000000e+00,
        5.50170339e-05, 2.00055017e-01]),
 array([1., 1., 0., 1., 0., 0.]),
 array([[0.65005501, 0.34994498],
        [0.23460912, 0.797671  ]]),
 [0.39999999999999986,
  0.6807006667488207,
  0.5500550170339109,
  0.5500550170339109,
  0.5500550170339109,
  0.5500550170339109,
  0.5500550170339109,
  0.5500550170339109,
  0.5500550170339109,
  0.5500550170339109,
  0.5500550170339109,
  0.5500550170339109,
  0.5500550170339109,
  0.5500550170339109,
  0.5500550170339109,
  0.5500550170339109],
 [],
 [0.7638170019537753,
  1.3183347464017314,
  1.3183347464017314,
  1.3183347464017314,
  1.3183347464017314,
  1.3183347464017314,
  1.3183347464017314,
  1.3183347464017314,
  1.3183347464017314,
  1.3183347464017314,
  1.3183347464017314,
  1.3183347464017314,
  1.3183347464017314,
  1.3183347464017314,
  1.3183347464017314,
  1.3183347464017314])

In [14]:
from data import load_preprocessing
import numpy as np

In [15]:
data_path = './data/' + 'r8-emd_tr_te3dict70.pkl'

In [16]:
data = load_preprocessing(data_path)
p = 1
C = data['cost_T']
Data = data['X']
Data_lda = data['proportions']
y = data['y']
k = np.unique(y).shape[0]

In [17]:
k

8